import { NextResponse } from "next/server";
import { createClient } from "@/lib/supabase/server";

export const dynamic = "force-dynamic";

// GET /api/account/licenses
// License records are generated by admin and do not have a userId field,
// so we cannot automatically link them to a Supabase auth account.
// Returns an empty array; users must contact support to claim licenses.
export async function GET() {
  const supabase = createClient();
  const { data: { user } } = await supabase.auth.getUser();
  if (!user) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });

  return NextResponse.json([]);
}
